### ISSUE TITLE
add the file location (what device) to the files table [$50]

### ISSUE THREAD

**Issue by mmills6060** [Banbury-inc/Athena#37]

**Comment by prithvi009** [comment]
I want to contribute to this issue.....can you provide more details on the issue?

**Comment by mmills6060** [comment]
@prithvi009 This is the table I need work on. 

https://github.com/Banbury-inc/Athena/blob/main/Banbury_Cloud/frontend/src/renderer/components/Table.tsx

Right now, I am able to get pieces of information such as file name, file size, and date uploaded. 

you can see how the api call returns information here 

https://website2-v3xlkt54dq-uc.a.run.app/getuserinfo/

I want to create a column in this table that tells the user what device the file is located in. This data can be taken from the api url above. all done in typescript. Thank you.

**Comment by prithvi009** [comment]
Hey! Just wanted to ask about the pr that was merged how can I claim the bounty?

**Comment by mmills6060** [comment]
complete
