### ISSUE TITLE
create registration page frontend [$50]

### ISSUE THREAD

**Issue by mmills6060** [Banbury-inc/Athena#52]

**Comment by prithvi009** [comment]
Hey! can you provide details for entries?

**Comment by dv2202** [comment]
I'm eager to contribute to the frontend registration page. Could you please provide details? Thanks!

**Comment by Deb-cybe** [comment]
Hi @mmills6060 , I'm interested in contributing to this issue. 
Let me know if there are any specific requirements, guidelines, or preferences I should follow while working on this issue.

**Comment by mmills6060** [comment]
done
