### ISSUE TITLE
create registration page backend [$50]

### ISSUE THREAD

**Issue by mmills6060** [Banbury-inc/Athena#53]

**Comment by avdhendra** [comment]
hi @mmills6060 can you assign this bounty to me and can you tell me what are the field required for registration for your page in majorly there  are name,email,password,confirmpassword but if there are more you need you can put it in readme file

**Comment by mmills6060** [comment]
Please use this material UI template. 

https://github.com/mui/material-ui/tree/v5.15.11/docs/data/material/getting-started/templates/sign-up

Required fields: 
1. username
2. password (box for confirm password)

Optional fields for the user:
1. first name
2. last name
3. phone number
4. email

ensure theme is going through my own theme.tsx

get the registration link in log in page to route to this registration page.

thank you!

**Comment by mmills6060** [comment]
done
